[package]
name = "calculator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# [[bin]]
# name = "calculator"
# path = "src/main.rs"


[dependencies]
wasm-bindgen = "0.2"    
meval = "0.2.0"